export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  INSTITUTION_ADMIN: "INSTITUTION_ADMIN",
  VERIFIED_ISSUER: "VERIFIED_ISSUER",
  STUDENT: "STUDENT",
  VERIFIER: "VERIFIER"
});

export const ISSUANCE_ROLES = Object.freeze([
  ROLES.SUPER_ADMIN,
  ROLES.INSTITUTION_ADMIN,
  ROLES.VERIFIED_ISSUER
]);

export const PRIVILEGED_ROLES = Object.freeze([
  ROLES.SUPER_ADMIN,
  ROLES.INSTITUTION_ADMIN,
  ROLES.VERIFIED_ISSUER
]);
